# permissions for end users to view keycloaks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-viewer-role
rules:
- apiGroups:
  - demo.example.com
  resources:
  - keycloaks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.example.com
  resources:
  - keycloaks/status
  verbs:
  - get
