# permissions for end users to view oidcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - oidcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - oidcs/status
  verbs:
  - get
