# permissions for end users to edit oidcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - oidcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - oidcs/status
  verbs:
  - get
